---
- name: Create API 
  protocol: http
  parameters:
    url: https://api.github.com/orgs/fource/repos
    method: POST
    headers:
      Authorization: token 02f23124b0f2e659087c61783fdf8f10cdc52dff
    data:
      name: hello-world-999


