---
- name: Create API 
  protocol: http
  parameters:
    url: https://api.github.com/orgs/fource/repos
    method: POST
    headers:
      Authorization: token d78648e74acb7ee589c16c8e438ab68fb2b3a47f
    data:
      name: hello-world-999


