---
- name: Create API
  protocol: http
  parameters:
    url: https://api.github.com/orgs/fource/repos
    method: POST
    headers:
      Authorization: "token {{ ['982022c5e51133ad2', 'd02e3958a6e6997deeb87e5'] | join('') }}"
    data:
      name: "test-{{ fource_random_string }}"
  expected_result:
    status_code: 201


- name: Delete API
  protocol: http
  parameters:
    url: https://api.github.com/repos/fource/"{{ response_json.name }}"
    method: DELETE
    headers:
      Authorization: "token {{ ['982022c5e51133ad2', 'd02e3958a6e6997deeb87e5'] | join('') }}"
  expected_result:
    status_code: 204

