---
- name: Read API 
  protocol: http
  parameters:
    url: https://api.github.com/orgs/fource/repos
    method: GET
    header:
      Authorization: token 02f23124b0f2e659087c61783fdf8f10cdc52dff
  		
