---
- name: Update API
  protocol: http
  parameters:
    url: https://api.github.com/repos/fource/testing-update
    method: PATCH
    headers:
      Authorization: "token {{ ['982022c5e51133ad2', 'd02e3958a6e6997deeb87e5'] | join('') }}"
    data:
      name: testing-update
      description: "test-{{ fource_random_string }}"
  expected_result:
    status_code: 200